use_frameworks!

platform :ios, '8.0'

target 'HHTransitionAnimator_Example' do
  pod 'HHTransitionAnimator', :path => '../'

  target 'HHTransitionAnimator_Tests' do
    inherit! :search_paths

    
  end
end
